### ISSUE TITLE
Optional Config: D-Pad requires Direction + D-Pad Click to send [instead of taps]

### ISSUE THREAD

**Issue by sevdestruct** [zydeco/SteamController#3]
For use with oldschool systems being emulated, being able to hook an optional setting would be very helpful for dpad input to not feel so… foreign or accidental. After demoing this, I'd argue a user needs to find/feel for the dpad direction before input is sent to emulator, commiting the input in a single click release or held down fashion since those old systems are just basic buttons with no variable input on the receiving end beyond buttonPressed, buttonReleased… which the current light taps don't really match up to.

(would like to be able to hook this optional in [Provenance] app's settings externally)

**Comment by sevdestruct** [comment]
I've got the basics of this setup already on my local checkout (and some other revisions), working for up, down, right, left — i don't have combinations of those a/o single click diagonal directions working quite yet…

—also haven't set up optional for this but i may have another or alternate idea via switching a mode instead or additionally…

Saw you pop onto Discord for a moment. Hope to catch you later, have some other ideas your framework has inspired I wanted to talk to you about.

**Comment by zydeco** [comment]
This and other config options implemented in 04655cd7a33cb3e4f8ec0cb5db5f362399e7a7df.
Added properties in `SteamController`:

- `steamLeftTrackpadMapping`, `steamRightTrackpadMapping`, `steamThumbstickMapping`: allow changing the mapping of the Steam Controller's inputs to a different MFi equivalent.
- `steamLeftTrackpadRequiresClick`, `steamRightTrackpadRequiresClick`: if true, trackpads will only send input when clicked (not when touched)

**Comment by sevdestruct** [comment]
nice work, @zydeco

I added some controller combo toggles to alt between modes, and some logic to avoid misfires on the buttons used for them.
