### ISSUE TITLE
Controller isn't redetected on reconnect…

### ISSUE THREAD

**Issue by sevdestruct** [zydeco/SteamController#4]
I need to test further on this, but seems like Steam Controller won't be redetected if it idles asleep and is turned on again…?

**Comment by zydeco** [comment]
I haven't found a way around this, it seems the only way to detect a controller is by scanning.

If the controller connects shortly after `scanForControllers` is called, it will be detected, presumably because the `CBCentralManager` is still scanning.

A possible workaround might be to call `scanForControllers` at appropriate times, like when starting or resuming a game.

**Comment by sevdestruct** [comment]
could we have an interval that checks this once a controller is detected missing?
or yes, i think at the point of resuming a game would be a good one for some key spots, especially since controller missing usually pauses the game.

**Comment by sevdestruct** [comment]
Could also write something for the pause menu to rescan for the controller manually as your demo app does, since it wont be automatic like MFi controllers are…

**Comment by sevdestruct** [comment]
**Potential Solution:** If possible, have the scan for steam controller initiate every time a device is reported connected to iOS/tvOS (system).

**Comment by zydeco** [comment]
> **Potential Solution:** If possible, have the scan for steam controller initiate every time a device is reported connected to iOS/tvOS (system).

This is only possible through IOKit, which is private API on iOS, I've started implementing it on the [auto-reconnect](https://github.com/zydeco/SteamController/tree/auto-reconnect) branch.
Will probably end up wrapping it in a compile-time flag, so it can be left out of the binary if you don't want to use private API.

**Comment by zydeco** [comment]
Implemented in 92efac3
